<?php
$prompt = "<div id='prompt' class='container'>";
$prompt .= "<form action='controller.php' method='post'>";
$prompt .= "<div class='form-group'>";
$prompt .= "<div class='row'>";
$prompt .= "<div class='col-sm-6'>";
$prompt .= "<div id='accordion'>";
$prompt .= "<div class='card'>";
$prompt .= "<div class='card-header' id='headingThree'>";
$prompt .= "<h5 class='mb-0'>";
$prompt .= "<button class='btn btn-link' data-toggle='collapse' data-target='#collapseThree' aria-expanded='true' aria-controls='collapseThree'>Prompt Table</button>";
$prompt .= '</h5>';
$prompt .= '</div>';
$prompt .= "<div id='collapseThree show' class='collapse show' aria-labelledby='headingThree' data-parent='#accordion'>";
$prompt .= "<div class='card-body'>";
$prompt .= "<table class='table'>";
$prompt .= "<thead id='head-dark' class='thead-dark'>";
$prompt .= '<tr>';
$prompt .= "<th scope='col'>PROMPT</th>";
$prompt .= "<th scope='col'>NAME</th>";
$prompt .= "<th scope='col'>CONTROLS</th>";
$prompt .= '</tr>';
$prompt .= '</thead>';
$prompt .= '<tbody>';
$prompt .= '<tr>';
$prompt .= '<td>';
$prompt .= "<div class='input-group input-group-default mb-6'>";
$prompt .= "<div class='input-group-prepend'>";
$prompt .= "<div class='input-group-text' id='inputGroup-sizing-sm'>$row[nametext]</div>";
$prompt .= '</div>';
$prompt .= '</div>';
$prompt .= '</td>';
$prompt .= '<td>';
$prompt .= "<div class='input-group-append'>";
$prompt .= "<input type='text' name='collectiontext[]' class='form-control' aria-label='Small' aria-describedby='inputGroup-sizing-lg'>";
$prompt .= '</div>';
$prompt .= '</td>';
$prompt .= '<td>';
$prompt .= "<div class='input-group-append'>";
$prompt .= "<button class='btn btn-primary' type='submit' title='Click to Submit'>SUBMIT</button>";
$prompt .= '</div>';
$prompt .= '</td>';
$prompt .= '</tr>';
$prompt .= '</tbody>';
$prompt .= '</table>';
$prompt .= '</div>';
$prompt .= '</div>';
$prompt .= '</div>';
$prompt .= '</div>';
$prompt .= '</div>';
$prompt .= '</div>';
$prompt .= '</div>';
$prompt .= "<input type='hidden' name='action' value='insert'>";
$prompt .= '</form>';


$collection = "<div id='collection' class='col-sm-6'>";
$collection .= "<form action='controller.php' method='post'>";
$collection .= "<div id='accordion'>";
$collection .= "<div class='card'>";
$collection .= "<div class='card-header' id='headingThree'>";
$collection .= "<h5 class='mb-0'>";
$collection .= "<button class='btn btn-link' data-toggle='collapse' data-target='#collapseThree' aria-expanded='true' aria-controls='collapseThree'>Collection Table</button>";
$collection .= '</h5>';
$collection .= '</div>';
$collection .= "<div id='collapseThree show' class='collapse show' aria-labelledby='headingThree' data-parent='#accordion'>";
$collection .= "<div class='card-body'>";
$collection .= "<table class='table'>";
$collection .= "<thead id='head-dark' class='thead-dark'>";
$collection .= '<tr>';
$collection .= "<th scope='col'>PROMPT</th>";
$collection .= "<th scope='col'>NAME</th>";
$collection .= "<th scope='col'>CONTROLS</th>";
$collection .= '</tr>';
$collection .= '</thead>';
$collection .= '<tbody>';
$collection .= '<tr>';
$collection .= '<td>';
$collection .= "<div class='input-group input-group-default mb-6'>";
$collection .= "<div class='input-group-prepend'>";
$collection .= "<div class='input-group-text' id='inputGroup-sizing-sm'>$row[collectiontext]</div>";
$collection .= '</div>';
$collection .= '</div>';
$collection .= '</td>';
$collection .= '<td>';
$collection .= "<div class='input-group-append'>";
$collection .= "<input type='text' class='form-control' aria-label='Small' aria-describedby='inputGroup-sizing-lg'>";
$collection .= '</div>';
$collection .= '</td>';
$collection .= '<td>';
$collection .= "<div class='input-group-append'>";
$collection .= "<button type='button' class='btn btn-warning' title='Click to Update'><i class='fas fa-sync-alt fa-fw'></i></button>";
$collection .= "<button type='button' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalCenter' title='Click to Delete'><i class='fas fa-trash-alt fa-fw'></i></button>";
$collection .= '</div>';
$collection .= '</td>';
$collection .= '</tr>';
$collection .= '</tbody>';
$collection .= '</table>';
$collection .= '</div>';
$collection .= '</div>';
$collection .= '</div>';
$collection .= '</div>';
$collection .= '</form>';
$collection .= '</div>';
$collection .= '</div>';
?>
